config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to:'static_pages#home'

  get "/:category/products", to: "products#index", as: "products"
  get "/products/new", to: "products#new"
  post "/products/new", to: "products#create"
  get "/:category/products/:slug", to: "products#show", as: "products_show"
  get "/products/:id", to: "products#show_json"

  get "/profile/purchase", to: "profile#purchase"
  get "/profile/sale", to: "profile#sale"
  get "/profile/balance", to: "profile#balance"
  get "/profile/cart", to: "profile#cart"
  get "/profile/ads", to: "profile#ads"
  patch "/products/:slug/delist", to: "products#delist", as: "products_delist"
  patch "/products/:slug/relist", to: "products#relist", as: "products_relist"

  patch "/profile/balance/bank_detail", to: "profile#edit_bank_detail", as: "edit_bank_detail"
  patch "/profile/balance/balance", to: "profile#edit_balance", as: "edit_balance"

  post "/profile/transaction", to: "profile#create_transaction", as: "create_transaction"

  post "/comments/new", to: "comments#new"
  delete "/comments/:id/delete", to: "comments#delete", as: "comments_delete"
  post "/comments/:id/reply/new", to: "comments#reply_new", as: "comments_reply_new"
  delete "/comments/:id/reply/delete", to: "comments#reply_delete", as: "comments_reply_delete"

  post "/transactions/create", to: "transactions#create"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @categories = Category.all[0..3]
    @products = Product.where(listed: true)[0..7]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<%= render "shared/navbar" %>
<%= render "shared/hero" %>

<div class="px-4 bg-gray-50">
    <div class="max-w-6xl mx-auto grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 md:gap-4 py-8">
        <% if @products.count == 0 %>
            <article class="p-4 text-gray-900 text-center font-bold col-span-full">
                No products found
            </article>
        <% end %>
        <% @products.each do |product| %>
            <%= link_to products_show_path(category: "all", slug: product.slug) do %>
                <article class="bg-white rounded-sm p-2 shadow text-gray-900 hover:shadow-lg transform hover:-translate-y-0.5 duration-300 ease-in-out">
                    <div class="bg-gray-100 mb-2 flex justify-center h-32 sm:h-40 relative">
                        <%= image_tag product.product_images.first.image, class: "object-contain" %>
                        <div class="hidden sm:block bg-black bg-opacity-60 px-3.5 py-2 text-white absolute top-2/3 -left-2 font-medium">
                            <span class="text-green-500">$</span>
                            <%= number_to_currency product.price/100.0, unit: "" %>
                        </div>
                    </div>
                    <div>
                        <p class="text-sm"><%= product.title.truncate(40) %></p>
                        <p class="sm:hidden text-sm font-medium text-green-500">$ <%= number_to_currency product.price/100.0, unit: "" %></p>
                    </div>
                </article>
            <% end %>
        <% end %>
    </div>
    <div class="flex justify-center items-center pb-16">
        <%= link_to "See all", products_path(category: "all"), class: "py-3 px-12 border-2 border-green-500 font-medium rounded-sm text-gray-900 bg-transparent hover:bg-green-500 hover:text-white focus:outline-none focus:border-green-500 focus:shadow-outline-green transition duration-150 ease-in-out cursor-pointer" %>
    </div>
</div>

<%= javascript_pack_tag 'navbar' %>
<%= javascript_pack_tag 'hero' %>