config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to:'static_pages#home'

  get "/:category/products", to: "products#index", as: "products"
  get "/products/new", to: "products#new"
  post "/products/new", to: "products#create"
  get "/:category/products/:slug", to: "products#show", as: "products_show"
  get "/products/:id", to: "products#show_json"

  get "/profile/purchase", to: "profile#purchase"
  get "/profile/sale", to: "profile#sale"
  get "/profile/balance", to: "profile#balance"
  get "/profile/cart", to: "profile#cart"
  get "/profile/ads", to: "profile#ads"
  patch "/products/:slug/delist", to: "products#delist", as: "products_delist"
  patch "/products/:slug/relist", to: "products#relist", as: "products_relist"

  patch "/profile/balance/bank_detail", to: "profile#edit_bank_detail", as: "edit_bank_detail"
  patch "/profile/balance/balance", to: "profile#edit_balance", as: "edit_balance"

  post "/profile/transaction", to: "profile#create_transaction", as: "create_transaction"

  post "/comments/new", to: "comments#new"
  delete "/comments/:id/delete", to: "comments#delete", as: "comments_delete"
  post "/comments/:id/reply/new", to: "comments#reply_new", as: "comments_reply_new"
  delete "/comments/:id/reply/delete", to: "comments#reply_delete", as: "comments_reply_delete"

  post "/transactions/create", to: "transactions#create"
end

app/views/shared/_footer.html.erb
<footer class="p-8 flex flex-col items-center text-gray-600 border-t">
    <div class="mb-4">
        <a href="https://www.facebook.com/" class="text-xl px-2 py-1 mx-1 rounded-md hover:bg-green-100 transition ease-in-out duration-150"><i class="fab fa-facebook-f"></i></a>
        <a href="https://www.instagram.com/" class="text-xl px-2 py-1 mx-1 rounded-md hover:bg-green-100 transition ease-in-out duration-150"><i class="fab fa-instagram"></i></a>
        <a href="https://twitter.com/" class="text-xl px-2 py-1 mx-1 rounded-md hover:bg-green-100 transition ease-in-out duration-150"><i class="fab fa-twitter"></i></a>
    </div>
    <%= link_to "Minima", root_path, class: "mb-4 font-medium bg-green-500 px-3 py-2 text-white", style: "border-radius: 50%;" %>
    <div class="text-sm">
        Copyright &copy; <span id="year"></span> Minima
    </div>
</footer>

<%= javascript_pack_tag 'footer' %>

app/views/shared/_hero.html.erb
<div id="hero" class="px-4">
    <div class="relative z-10 max-w-6xl mx-auto">
        <div class="flex justify-end mb-8">
            <%= link_to "Post an Ad", products_new_path, class: "mt-8 py-2 px-4 border border-transparent text-sm font-medium rounded-sm text-white bg-green-500 hover:bg-green-400 focus:outline-none focus:border-green-500 focus:shadow-outline-green transition duration-150 ease-in-out cursor-pointer" %>
        </div>
        <p class="text-center text-2xl md:text-3xl font-extrabold text-white mb-8">Why waste, when you can sell for extra cash?</p>
        <%= form_with url: products_path(category: "all"), method: :get, class: "py-6 md:py-8 px-8 md:px-10 bg-black bg-opacity-50", id: "search-form" do |form| %>
            <div class="flex flex-col sm:flex-row">
                <%= form.select :category, options_for_select([["All", "all"]] + @categories.map { |category| [category.title.capitalize, category.slug] }, selected: @category.nil? ? "all" : (@category == "all" ? "all" : @category.slug)), {}, {class: "px-4 md:px-6 py-2 md:py-4 border border-gray-300 shadow-sm focus:outline-none focus:border-green-500 text-sm md:text-lg mb-2 sm:mb-0"} %>
                <div class="flex sm:flex-grow">
                    <%= form.text_field :search, class: "flex-grow px-4 md:px-6 py-2 md:py-4 border border-gray-300 shadow-sm focus:outline-none focus:border-green-500 text-sm md:text-lg", autocomplete: "off", placeholder: "I am looking for...", id: "search-input", value: @search.nil? ? "" : @search %>
                    <%= form.submit "Search", class: "px-3 py-2  border border-transparent text-sm md:text-lg font-medium text-white bg-green-500 hover:bg-green-400 focus:outline-none focus:border-green-500 focus:shadow-outline-green transition duration-150 ease-in-out cursor-pointer" %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="flex justify-center bg-gray-200 shadow-md px-2 border-b border-gray-300 bg-opacity-90">
    <div class="flex flex-col md:flex-row md:justify-between container">
        <div class="flex flex-col md:flex-row md:justify-between">
            <div class="flex justify-between items-center">
                <%= link_to "Minima", root_path, class: "my-2 font-medium bg-green-500 px-3 py-2 text-white", style: "border-radius: 50%;" %>
                <button class="w-8 h-8 md:hidden text-xl text-gray-700 hover:bg-white transition ease-in-out duration-150 rounded-md" id="navbar__btn"><i class="fas fa-bars"></i></button>
            </div>
            <ul class="hidden md:flex flex-col md:flex-row text-sm font-medium md:ml-5" id="navbar__menu1">
                <% @categories.each do |category| %>
                    <li class="hover:bg-white text-gray-700 transition ease-in-out duration-150 rounded-md md:rounded-none"><%= link_to category.title, products_path(category: category.slug), class: "block p-5 leading-4", style: "height: 56px;" %></li>
                <% end %>
                <li class="hover:bg-white hover:text-gray-700 transition ease-in-out duration-150 rounded-md md:rounded-none"><%= link_to "More...", products_path(category: "all"), class: "block p-5 leading-4", style: "height: 56px;" %></li>
            </ul>
        </div>
        <ul class="hidden md:flex justify-center" id="navbar__menu2">
            <% if user_signed_in? %>
                <div class="flex items-center px-1" style="height: 56px;">
                    <%= link_to profile_cart_path, class: "text-2xl py-1 px-1.5 hover:bg-white text-gray-700 transition ease-in-out duration-150 rounded-md relative" do %>
                        <i class="fas fa-shopping-cart"></i>
                        <div class="absolute top-0 right-0 text-xs bg-white flex justify-center items-center rounded-full w-5 h-5 text-green-500 font-medium" id="navbar__cart"></div>
                    <% end %>
                </div>
                <div class="flex items-center px-1 relative" style="height: 56px;">
                    <button class="text-2xl py-1 px-1.5 hover:bg-white text-gray-700 transition ease-in-out duration-150 rounded-md" id="user__btn"><i class="far fa-user-circle"></i><i class="fas fa-caret-down text-base align-middle ml-0.5"></i></button>
                    <ul class="hidden absolute top-12 right-0 bg-white rounded text-gray-700 p-2 text-left shadow-lg min-w-max cursor-default text-sm z-50" id="user__dropdown">
                        <%# Tooltip start %>
                        <svg
                            class="absolute text-white h-2 right-0 mr-3 bottom-full"
                            x="0px"
                            y="0px"
                            viewBox="0 0 1500 1000"
                            xmlSpace="preserve"
                        >
                                <polygon
                                    class="fill-current"
                                    points="750,0 1500,1000, 0,1000"
                                />
                        </svg>
                        <%# Tooltip end %>
                        <li>
                            <div href="#" class="p-2 block text-sm font-semibold">
                                Signed in as <%= current_user.username %>
                            </div>
                        </li>
                        <hr/>
                        <li class="hover:bg-gray-100 rounded transition-colors duration-150">
                            <%= link_to profile_ads_path, class: "p-2 flex items-center cursor-pointer w-full" do %>
                                <span class="mr-2 text-green-500">
                                    <i class="fas fa-ad"></i>
                                </span>
                                My Ads
                            <% end %>
                        </li>
                        <li class="hover:bg-gray-100 rounded transition-colors duration-150">
                            <%= link_to profile_purchase_path, class: "p-2 flex items-center cursor-pointer w-full" do %>
                                <span class="mr-2 text-green-500">
                                    <i class="fas fa-shopping-bag"></i>
                                </span>
                                Purchase history
                            <% end %>
                        </li>
                        <li class="hover:bg-gray-100 rounded transition-colors duration-150">
                            <%= link_to profile_sale_path, class: "p-2 flex items-center cursor-pointer w-full" do %>
                                <span class="mr-2 text-green-500">
                                    <i class="fas fa-store"></i>
                                </span>
                                Sale history
                            <% end %>
                        </li>
                        <li class="hover:bg-gray-100 rounded transition-colors duration-150">
                            <%= link_to profile_balance_path, class: "p-2 flex items-center cursor-pointer w-full" do %>
                                <span class="mr-2 text-green-500">
                                    <i class="fas fa-wallet"></i>
                                </span>
                                My balance
                            <% end %>
                        </li>
                        <hr/>
                        <li class="hover:bg-gray-100 rounded transition-colors duration-150">
                            <%= link_to destroy_user_session_path, method: :delete, class: "p-2 flex items-center cursor-pointer w-full" do %>
                                <span class="mr-2 text-green-500">
                                    <i class="fas fa-sign-out-alt"></i>
                                </span>
                                Logout
                            <% end %>
                        </li>
                    </ul>
                </div>
            <% else %>
                <li class="flex items-center px-1" style="height: 56px;">
                    <%= link_to profile_cart_path, class: "text-2xl py-1 px-1.5 hover:bg-white text-gray-700 transition ease-in-out duration-150 rounded-md relative" do %>
                        <i class="fas fa-shopping-cart"></i>
                        <div class="absolute top-0 right-0 text-xs bg-white flex justify-center items-center rounded-full w-5 h-5 text-green-500 font-medium" id="navbar__cart"></div>
                    <% end %>
                </li>
                <li class="text-gray-700 text-sm font-medium hover:bg-white transition ease-in-out duration-150 rounded-md md:rounded-none"><%= link_to "Sign in", new_user_session_path, class: "block p-5 leading-4", style: "height: 56px;" %></li>
                <li class="text-gray-700 text-sm font-medium hover:bg-white transition ease-in-out duration-150 rounded-md md:rounded-none"><%= link_to "Register", new_user_registration_path, class: "block p-5 leading-4", style: "height: 56px;" %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/shared/_navbar_simple.html.erb
<nav class="flex justify-center bg-gray-200 shadow-md px-2 border-b border-gray-300 bg-opacity-90">
    <div class="container">
        <div class="flex justify-between items-center">
            <%= link_to "Minima", root_path, class: "my-2 font-medium bg-green-500 px-3 py-2 text-white", style: "border-radius: 50%;" %>
            <% if user_signed_in? %>
                <div class="p-3">
                    <button class="w-8 h-8 text-xl"><i class="far fa-user-circle"></i></button>
                </div>
            <% end %>
        </div>
    </div>
</nav>