config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  root to:'static_pages#home'

  get "/:category/products", to: "products#index", as: "products"
  get "/products/new", to: "products#new"
  post "/products/new", to: "products#create"
  get "/:category/products/:slug", to: "products#show", as: "products_show"
  get "/products/:id", to: "products#show_json"

  get "/profile/purchase", to: "profile#purchase"
  get "/profile/sale", to: "profile#sale"
  get "/profile/balance", to: "profile#balance"
  get "/profile/cart", to: "profile#cart"
  get "/profile/ads", to: "profile#ads"
  patch "/products/:slug/delist", to: "products#delist", as: "products_delist"
  patch "/products/:slug/relist", to: "products#relist", as: "products_relist"

  patch "/profile/balance/bank_detail", to: "profile#edit_bank_detail", as: "edit_bank_detail"
  patch "/profile/balance/balance", to: "profile#edit_balance", as: "edit_balance"

  post "/profile/transaction", to: "profile#create_transaction", as: "create_transaction"

  post "/comments/new", to: "comments#new"
  delete "/comments/:id/delete", to: "comments#delete", as: "comments_delete"
  post "/comments/:id/reply/new", to: "comments#reply_new", as: "comments_reply_new"
  delete "/comments/:id/reply/delete", to: "comments#reply_delete", as: "comments_reply_delete"

  post "/transactions/create", to: "transactions#create"
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :category
  belongs_to :user

  has_many :product_images
  has_many :comments
  has_many :transactions

  validates :title, presence: true
  validates :description, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0 }
  validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  self.per_page = 5
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action  :get_categories
  before_action :authenticate_user!, only: [:create, :new, :delist, :relist, :edit]

  def index
    category_slug = params[:category]
    min_price = params[:min_price].nil? ? nil : params[:min_price].to_f * 100
    max_price = params[:max_price].nil? ? nil : params[:max_price].to_f * 100
    @search = params[:search]

    if category_slug == 'all'
      @category = 'all'

      if min_price && max_price
        @products = Product.where("price >= ?", min_price).where("price <= ?", max_price).where(listed: true).paginate(page: params[:page])
      elsif min_price
        @products = Product.where("price >= ?", min_price).where(listed: true).paginate(page: params[:page])
      elsif max_price
        @products = Product.where("price <= ?", max_price).where(listed: true).paginate(page: params[:page])
      else
        @products = Product.where(listed: true).paginate(page: params[:page])
      end

      if @search
        @products = @products.where(listed: true).where("title ilike ?", "%#{@search}%").paginate(page: params[:page])
      end

      @category_counts = Product.where(listed: true).group(:category_id).count
      @min_price = min_price.nil? ? nil : min_price /100
      @max_price = max_price.nil? ? nil : max_price /100
    else
      category = Category.find_by slug: category_slug

      if !category
        redirect_to products_path(category: "all")
        return
      else
        @category = category

        if min_price && max_price
          @products = category.products.where("price >= ?", min_price).where("price <= ?", max_price).where(listed: true).paginate(page: params[:page])
        elsif min_price
          @products = category.products.where("price >= ?", min_price).where(listed: true).paginate(page: params[:page])
        elsif max_price
          @products = category.products.where("price <= ?", max_price).where(listed: true).paginate(page: params[:page])
        else
          @products = category.products.where(listed: true).paginate(page: params[:page])
        end

        if @search
          @products = @products.where("title ilike ?", "%#{@search}%").where(listed: true).paginate(page: params[:page])
        end

        @category_counts = Product.where(listed: true).group(:category_id).count
        @min_price = min_price.nil? ? nil : min_price /100
        @max_price = max_price.nil? ? nil : max_price /100
      end
    end
  end

  def show
    category_slug = params[:category]

    if category_slug == 'all'
      @category = 'all'

      begin
        @product = Product.where(listed: true).friendly.find(params[:slug])
      rescue ActiveRecord::RecordNotFound
        @product = nil
        @slug = params[:slug]
      end
    else
      category = Category.find_by slug: category_slug

      if !category
        redirect_to products_show_path(category: "all", slug: params[:slug])
        return
      else
        @category = category

        begin
          @product = @category.products.where(listed: true).friendly.find(params[:slug])
        rescue ActiveRecord::RecordNotFound
          @product = nil
          @slug = params[:slug]
        end
      end
    end
  end

  def show_json
    id = params[:id].to_i
    
    begin
      product = Product.where(listed: true).find(id)
      product_image = url_for(product.product_images.first.image)
      product = product.as_json
      product[:image] = product_image
    rescue ActiveRecord::RecordNotFound
      product = nil
    end

    render json: product
  end

  def create
    begin
      category = Category.friendly.find(params[:category])
    rescue ActiveRecord::RecordNotFound
      flash[:alert_ad] = ["Invalid category was provided"]
      redirect_to products_new_path
      return
    end

    if params[:product_images].nil? || params[:product_images].length > 3
      flash[:alert_ad] = ["You need to provide between 1 and 3 images."]
      redirect_to products_new_path
      return
    end

    product = Product.new
    ActiveRecord::Base.transaction do
      product.title = params[:title]
      product.description = params[:description]
      product.price = params[:price].to_i
      product.stock = params[:stock].to_i
      product.category_id = category.id
      product.user_id = current_user.id
      product.save

      if product.invalid?
        flash[:alert_ad] = product.errors.full_messages
        redirect_to products_new_path
        return
      end

      params[:product_images].each do |product_image_param|
        product_image = ProductImage.new
        product_image.image.attach(product_image_param)
        product_image.product_id = product.id
        product_image.save
      end
    end

    flash[:success_ad] = "You've listed a new Ad for a product titled '#{product.title}'."
    redirect_to profile_ads_path
  end

  def new
  end

  def delist
    product = Product.friendly.find(params[:slug])
    if product.user == current_user
      if product.listed
        product.listed = false
        product.save
        flash[:success_ad] = "You've delisted an Ad for a product titled '#{product.title}'."
      else
        flash[:alert_ad] = "Your Ad for a product titled '#{product.title}' is already delisted."
      end
    else
      flash[:alert_ad] = "Your do not have permission to delist an Add for a product titled '#{product.title}'."
    end
    redirect_to profile_ads_path
  end

  def relist
    product = Product.friendly.find(params[:slug])
    if product.user == current_user
      if !product.listed
        product.listed = true
        product.save
        flash[:success_ad] = "You've relisted an Ad for a product titled '#{product.title}'."
      else
        flash[:alert_ad] = "Your Ad for a product titled '#{product.title}' is already listed."
      end
    else
      flash[:alert_ad] = "Your do not have permission to delist an Add for a product titled '#{product.title}'."
    end
    redirect_to profile_ads_path
  end

  private

  def get_categories
    @categories = Category.all
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/hero" %>

<div class="px-4 bg-gray-50">
    <div class="max-w-6xl mx-auto py-8">
        <div class="grid grid-cols-7 gap-8">
            <aside class="md:col-span-2 col-span-full text-gray-900">
                <div class="mb-4">
                    <p class="text-sm mb-1"><%= link_to "Home", root_path, class: "hover:underline" %><i class="fas fa-chevron-right text-xs mx-2 text-gray-400"></i><%= link_to @category == "all" ? "All" : @category.title, @category == "all" ? products_path(category: "all") : products_path(category: @category.slug), class: "hover:underline" %><i class="fas fa-chevron-right text-xs mx-2 text-gray-400"></i></p>
                    <% if @search && @search.strip != "" %>
                        <p class="text-xl tracking-wide"><%= @products.count %> <%= "result".pluralize(@products.count).capitalize %>: <span class="font-bold"><%= @search %></span></p>
                    <% else %>
                        <p class="text-xl tracking-wide"><%= @products.count %> <%= "result".pluralize(@products.count).capitalize %>
                    <% end %>
                </div>
                <div>
                    <ul>
                        <li class="px-1 py-2 block font-bold">Categories</li>
                        <li>
                            <% if @category == 'all' %>
                                <%= link_to products_path(category: "all"), class: "transition-colors duration-150 px-2 py-2 block rounded-sm hover:bg-gray-300 bg-gray-300" do %>
                                    All (<%= @category_counts.values.sum %>)
                                <% end %>
                            <% else %>
                                <%= link_to products_path(category: "all"), class: "transition-colors duration-150 px-2 py-2 block rounded-sm hover:bg-gray-300" do %>
                                    All (<%= @category_counts.values.sum %>)
                                <% end %>
                            <% end %>
                        </li>
                        <% @categories.each do |category| %>
                            <li>
                                <% if @category == category %>
                                    <%= link_to products_path(category: category.slug), class: "transition-colors duration-150 px-2 py-2 block rounded-sm hover:bg-gray-300 bg-gray-300" do %>
                                        <%= "#{category.title} (#{@category_counts[category.id].blank? ? 0 : @category_counts[category.id]})" %>
                                    <% end %>
                                <% else %>
                                    <%= link_to products_path(category: category.slug), class: "transition-colors duration-150 px-2 py-2 block rounded-sm hover:bg-gray-300" do %>
                                        <%= "#{category.title} (#{@category_counts[category.id].blank? ? 0 : @category_counts[category.id]})" %>
                                    <% end %>
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
                    <hr class="my-1" />
                    <ul>
                        <li class="px-1 py-2 block font-bold">Price</li>
                        <li>
                            <%= form_with url: products_path(category: @category == "all" ? "all" : @category.slug), method: :get, class: "flex flex-col" do |form| %>
                                <div class="grid grid-cols-2 gap-2 mb-2">
                                    <%= form.text_field :min_price, class: "border border-gray-300 shadow-sm focus:outline-none focus:border-green-500 text-sm p-2", autocomplete: "off", placeholder: "Min ($)", value: @min_price.nil? ? "" : @min_price %>
                                    <%= form.text_field :max_price, class: "border border-gray-300 shadow-sm focus:outline-none focus:border-green-500 text-sm p-2", autocomplete: "off", placeholder: "Max ($)", value: @max_price.nil? ? "" : @max_price %>
                                </div>
                                <%= form.hidden_field :search, value: @search, id: "search_input_hidden" %>
                                <%= form.submit "Search", class: "p-2 border-2 border-green-500 font-medium rounded-sm text-green-500 bg-transparent hover:bg-green-500 hover:text-white focus:outline-none focus:border-green-500 focus:shadow-outline-green transition duration-150 ease-in-out cursor-pointer" %>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </aside>
            <div class="md:col-span-5 col-span-full">
                <div class="grid gap-4">
                    <% if @products.count == 0 %>
                        <article class="p-4 text-gray-900 text-center font-bold">
                            No products found
                        </article>
                    <% else %>
                        <% @products.each do |product| %>
                            <%= link_to products_show_path(category: @category == "all" ? "all" : @category.slug, slug: product.slug), id: "products-index__product" do %>
                                <article class="flex flex-col sm:flex-row bg-white rounded-md p-4 shadow text-gray-900">
                                    <div class="w-36 h-36 flex justify-center items-center bg-gray-100">
                                        <%= image_tag product.product_images.first.image, class: "object-contain max-h-full" %>
                                    </div>
                                    <div class="flex flex-col justify-between sm:ml-4 flex-1">
                                        <div class="py-4 sm:py-0">
                                            <div class="flex justify-between">
                                                <p class="font-medium transition duration-150 ease-in-out" id="products-index__product-title"><%= product.title.capitalize %></p>
                                                <p class="font-medium"><%= number_to_currency product.price/100.0 %></p>
                                            </div>
                                            <p class="text-sm"><%= product.description.truncate(150) %></p>
                                        </div>
                                        <div class="flex justify-between items-center">
                                            <div></div>
                                            <p class="italic text-sm"><%= product.updated_at %></p>
                                        </div>
                                    </div>
                                </article>
                            <% end %>
                        <% end %>
                        <%= will_paginate @products %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<%= javascript_pack_tag 'navbar' %>
<%= javascript_pack_tag 'hero' %>

app/views/products/new.html.erb
<%= render "shared/navbar" %>

<div class="bg-gray-50 py-12 px-6 md:px-8">
    <div class="flex flex-col items-center">
        <h2 class="text-3xl font-extrabold text-gray-900">Post an Ad</h2>
    
    <%# model: @bank_detail, url: edit_bank_detail_path, method: :patch, class: "" %>

        <%= form_with url: products_new_path, class: "bg-white py-8 px-10 shadow rounded-lg my-8 max-w-md w-full", multipart: true do |f| %>
            <% if flash[:alert_ad] %>
                <ul class="rounded-md bg-red-400 p-4 mb-3 text-white">
                    <% flash[:alert_ad].each do |message| %>
                        <div class="px-5 text-sm">
                            <li class="list-disc"><%= message %></li>
                        </div>
                    <% end %>
                </ul>
            <% end %>
            <div class="field mb-5">
                <%= f.label :title, class: "block text-sm font-medium text-gray-700 mb-1" %>
                <%= f.text_field :title, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm" %>
            </div>

            <div class="field mb-5">
                <%= f.label :description, class: "block text-sm font-medium text-gray-700 mb-1" %>
                <%= f.text_area :description, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm", rows: 6 %>
            </div>

            <div class="field mb-5">
                <%= f.label :category, class: "block text-sm font-medium text-gray-700 mb-1" %>
                <%= f.select :category, options_for_select(@categories.map { |category| [category.title.capitalize, category.slug] }, selected: @category.nil? ? "all" : (@category == "all" ? "all" : @category.slug)), {}, {class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm"} %>
            </div>

            <div class="field mb-5">
                <%= f.label :price, class: "block text-sm font-medium text-gray-700 mb-1" do |label| %>
                    Price in cents
                <% end %>
                <%= f.number_field :price, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm" %>
            </div>

            <div class="field mb-5">
                <%= f.label :stock, class: "block text-sm font-medium text-gray-700 mb-1" %>
                <%= f.number_field :stock, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-sm" %>
            </div>

            <div class="field mb-5">
                <label class="block text-sm font-medium text-gray-700 mb-1">Images (up to 3 images)</label>
                <%= f.file_field :product_images, multiple: true, class: "text-sm", accept:'image/*' %>
            </div>

            <div class="actions">
                <%= f.submit "Post an Ad", class: "w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-500 hover:bg-green-400 focus:outline-none focus:border-green-500 focus:shadow-outline-green transition duration-150 ease-in-out cursor-pointer" %>
            </div>
        <% end %>
    </div>
</div>

<%= javascript_pack_tag 'navbar' %>